# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestNaoAssinado():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_naoAssinado(self):
    self.driver.get("https://ades.labsec.ufsc.br/")
    self.driver.set_window_size(1477, 695)
    self.driver.find_element(By.CSS_SELECTOR, ".btn > .material-symbols-outlined:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Português").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bt-verify a").click()
    self.driver.find_element(By.ID, "documentField").click()
    self.driver.find_element(By.ID, "documentField").send_keys("1")
    self.driver.find_element(By.ID, "sendFileBtn").click()
    self.driver.switch_to.frame(1)
    self.driver.execute_script("window.scrollTo(0,0)")
  
